### ISSUE TITLE
skywater-pdk documentation generation failing due to "annot import name 'ENOENT' from 'sphinx.util.osutil'" which is somehow related to sphinxcontrib_hdl_diagrams

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/sphinxcontrib-hdl-diagrams#75]
https://readthedocs.org/projects/skywater-pdk/builds/14408706/
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/registry.py", line 429, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinxcontrib_hdl_diagrams/__init__.py", line 45, in <module>
    from sphinx.util.osutil import ensuredir, ENOENT, EPIPE, EINVAL
ImportError: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/util/osutil.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/application.py", line 237, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/registry.py", line 432, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib_hdl_diagrams (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/util/osutil.py))

Extension error:
Could not import extension sphinxcontrib_hdl_diagrams (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/home/docs/checkouts/readthedocs.org/user_builds/skywater-pdk/conda/333/lib/python3.8/site-packages/sphinx/util/osutil.py))
```

**Comment by mithro** [comment]
@kgugala - Can you get someone to investigate this?
